### ISSUE TITLE
Example of linking without Lock

### ISSUE THREAD

**Issue by camiblanch** [auth0/auth0-link-accounts-sample#10]
Are there plans to create an example of linking and unlinking accounts not using Lock? It would be helpful since I don't plan on using Lock in my implementation. It might be useful to just add an example to the [auth0-javascript-samples](https://github.com/auth0-samples/auth0-javascript-samples) repository.

**Comment by zamd** [comment]
The express app is now updated to use universal login. 
https://github.com/auth0-samples/auth0-link-accounts-sample/pull/11

**Comment by zamd** [comment]
Both SPA and Regular Web Apps are updated to use Universal Login.  Closing this issue.
